In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import dateutil
from sklearn import svm
from sklearn import preprocessing
import timeit
import math

In [3]:
# get data in basic table form
df = pd.read_csv("./train_sample.csv")
df

,ip,app,device,os,channel,click_time,attributed_time,is_attributed
0,87540,12,1,13,497,2017-11-07 09:30:38,NaN,0
1,105560,25,1,17,259,2017-11-07 13:40:27,NaN,0
2,101424,12,1,19,212,2017-11-07 18:05:24,NaN,0
3,94584,13,1,13,477,2017-11-07 04:58:08,NaN,0
4,68413,12,1,1,178,2017-11-09 09:00:09,NaN,0
5,93663,3,1,17,115,2017-11-09 01:22:13,NaN,0
6,17059,1,1,17,135,2017-11-09 01:17:58,NaN,0
7,121505,9,1,25,442,2017-11-07 10:01:53,NaN,0
8,192967,2,2,22,364,2017-11-08 09:35:17,NaN,0
9,143636,3,1,19,135,2017-11-08 12:35:26,NaN,0
10,73839,3,1,22,489,2017-11-08 08:14:37,NaN,0
11,34812,3,1,13,489,2017-11-07 05:03:14,NaN,0
12,114809,3,1,22,205,2017-11-09 10:24:23,NaN,0
13,114220,6,1,20,125,2017-11-08 14:46:16,NaN,0
14,36150,2,1,13,205,2017-11-07 00:54:09,NaN,0
15,72116,25,2,19,259,2017-11-08 23:17:45,NaN,0
16,5314,2,1,2,477,2017-11-09 07:33:41,NaN,0
17,106598,3,1,20,280,2017-11-09 03:44:35,NaN,0
18,72065,20,2,90,259,2017-11-06 23:14:08,NaN,0
19,37301,14,1,13,349,2017-11-06 20:07:00,NaN,0
20,28735,12,1,19,265,2017-11-09 09:55:22,NaN,0
21,66918,64,1,25,459,2017-11-08 17:01:58,NaN,0
22,25761,9,1,10,215,2017-11-08 02:05:37,NaN,0
23,8362,7,1,19,101,2017-11-07 10:30:00,NaN,0
24,45257,3,1,18,280,2017-11-07 01:35:31,NaN,0
25,145896,64,1,13,459,2017-11-07 03:58:58,NaN,0
26,162976,3,1,13,115,2017-11-07 16:19:05,NaN,0
27,52432,1,1,13,115,2017-11-07 17:22:52,NaN,0
28,135690,12,1,40,122,2017-11-07 06:39:04,NaN,0
29,139137,12,1,13,497,2017-11-07 10:11:50,NaN,0
...,...,...,...,...,...,...,...,...
99970,57451,3,1,6,130,2017-11-09 13:35:55,NaN,0
99971,22529,3,1,22,173,2017-11-08 00:30:44,NaN,0
99972,118977,15,1,25,245,2017-11-07 05:02:52,NaN,0
99973,153487,2,1,42,477,2017-11-09 00:59:38,NaN,0
99974,13487,14,1,19,379,2017-11-08 08:08:40,NaN,0
99975,34029,14,1,13,467,2017-11-09 15:32:57,NaN,0
99976,6908,14,1,18,123,2017-11-07 22:59:12,NaN,0
99977,5788,18,1,58,439,2017-11-09 14:22:21,NaN,0
99978,190943,7,1,13,101,2017-11-09 11:47:49,NaN,0
99979,19162,9,1,37,489,2017-11-09 11:19:28,NaN,0
99980,111025,14,1,41,349,2017-11-08 12:58:11,NaN,0
99981,15651,10,1,1,377,2017-11-09 06:50:25,NaN,0
99982,5314,12,1,41,259,2017-11-09 02:09:20,NaN,0
99983,51379,3,1,41,135,2017-11-07 01:48:00,NaN,0
99984,185961,27,1,13,122,2017-11-07 05:02:01,NaN,0
99985,61500,3,1,10,280,2017-11-09 01:50:53,NaN,0
99986,119614,2,1,19,219,2017-11-07 11:27:54,NaN,0
99987,41851,11,1,28,319,2017-11-08 13:19:42,NaN,0
99988,69449,6,1,13,125,2017-11-09 13:53:30,NaN,0
99989,92730,3,1,19,379,2017-11-07 11:02:08,NaN,0
99990,84388,9,1,22,107,2017-11-09 04:21:28,NaN,0
99991,43374,1,1,18,134,2017-11-09 12:42:34,NaN,0
99992,125061,12,1,13,328,2017-11-07 09:33:14,NaN,0
99993,146258,3,1,13,280,2017-11-09 03:03:17,NaN,0
99994,147153,13,1,13,477,2017-11-07 07:34:13,NaN,0
99995,124883,11,1,19,122,2017-11-09 13:25:41,NaN,0
99996,85150,9,1,13,244,2017-11-07 11:25:43,NaN,0
99997,18839,3,1,13,19,2017-11-08 11:38:42,NaN,0
99998,114276,15,1,12,245,2017-11-08 17:55:21,NaN,0
99999,119349,14,1,15,401,2017-11-07 14:32:27,NaN,0

### Time to Attribution, hour of day, day of week, minute of hour

In [4]:
df['time_to_attribution'] = df.apply(lambda row: datetime.strptime(row['attributed_time'], '%Y-%m-%d %H:%M:%S') - datetime.strptime(row['click_time'], '%Y-%m-%d %H:%M:%S') if isinstance(row['attributed_time'], str) else '', axis=1)

df['hour_of_day'] = df.apply(lambda row: datetime.strptime(row['click_time'], '%Y-%m-%d %H:%M:%S').hour, axis=1)
df['day_of_week'] = df.apply(lambda row: datetime.strptime(row['click_time'], '%Y-%m-%d %H:%M:%S').weekday(), axis=1)
df['minute_of_hour'] = df.apply(lambda row: datetime.strptime(row['click_time'], '%Y-%m-%d %H:%M:%S').minute, axis=1)

print(df['day_of_week'].max())
print(df['day_of_week'].min())
print(df['hour_of_day'].max())
print(df['hour_of_day'].min())
print(df['minute_of_hour'].max())
print(df['minute_of_hour'].min())

3
0
23
0
59
0

### Click Frequency

In [5]:
df['click_time_dt'] = df.apply(lambda row: (dateutil.parser.parse(row['click_time'], dayfirst=True) - datetime.utcfromtimestamp(0)).total_seconds() , axis=1)


print(df['ip'].nunique())
ip = df['ip'].unique().tolist()
min_time = df.groupby('ip')["click_time_dt"].min().tolist()
max_time = df.groupby('ip')["click_time_dt"].max().tolist()
num_clicks = df.groupby('ip')["click_time_dt"].count().tolist()
ip

34857

[87540,
 105560,
 101424,
 94584,
 68413,
 93663,
 17059,
 121505,
 192967,
 143636,
 73839,
 34812,
 114809,
 114220,
 36150,
 72116,
 5314,
 106598,
 72065,
 37301,
 28735,
 66918,
 25761,
 8362,
 45257,
 145896,
 162976,
 52432,
 135690,
 139137,
 48846,
 70747,
 10831,
 89242,
 140138,
 28411,
 127888,
 75943,
 87879,
 250933,
 133933,
 35096,
 49431,
 53365,
 92599,
 107148,
 116677,
 11051,
 48240,
 92488,
 74999,
 123221,
 4019,
 40168,
 328403,
 134466,
 122354,
 104645,
 184757,
 3488,
 63994,
 52076,
 88604,
 9073,
 105861,
 25114,
 25876,
 61941,
 79827,
 99641,
 171729,
 257816,
 100494,
 5348,
 137208,
 81356,
 58128,
 71483,
 7521,
 100066,
 259930,
 30240,
 63109,
 36311,
 44494,
 111021,
 210555,
 6414,
 123729,
 73040,
 334558,
 123994,
 94536,
 127351,
 2600,
 99926,
 114878,
 173847,
 145747,
 94081,
 74725,
 51895,
 75431,
 104922,
 173247,
 124006,
 77310,
 61667,
 118349,
 46650,
 337099,
 34067,
 61635,
 145260,
 110245,
 77730,
 108831,
 124794,
 61706,
 91175,
 82618,
 81970,
 301417,
 187501,
 20295,
 25885,
 104753,
 191339,
 103208,
 92092,
 82427,
 47543,
 335694,
 175559,
 158312,
 108040,
 85072,
 197093,
 209540,
 79909,
 199702,
 40372,
 178124,
 18654,
 20309,
 74640,
 93460,
 80455,
 104729,
 58485,
 91885,
 111324,
 27342,
 153208,
 54868,
 278420,
 204614,
 85172,
 103161,
 59075,
 239191,
 85839,
 71424,
 63516,
 37919,
 43809,
 39454,
 8718,
 58950,
 86812,
 55805,
 175660,
 29785,
 88881,
 134615,
 34352,
 124320,
 80306,
 24830,
 195224,
 72805,
 93498,
 111685,
 83366,
 94844,
 105311,
 168144,
 20592,
 100002,
 37515,
 121357,
 63925,
 26995,
 37836,
 11090,
 65785,
 94765,
 98363,
 106241,
 112950,
 11668,
 105292,
 108048,
 113751,
 66232,
 69315,
 64663,
 69197,
 125481,
 143473,
 169833,
 75634,
 46132,
 111025,
 62145,
 191961,
 133804,
 61423,
 49850,
 151507,
 73456,
 88789,
 37892,
 234832,
 109299,
 12549,
 103443,
 46637,
 11907,
 98531,
 198014,
 47689,
 96037,
 3966,
 34725,
 285115,
 15540,
 49882,
 20411,
 33076,
 103021,
 313388,
 76453,
 175837,
 58614,
 49439,
 51544,
 334359,
 59142,
 246196,
 158559,
 68362,
 14130,
 24966,
 45745,
 67658,
 90306,
 23620,
 122292,
 57335,
 159688,
 93226,
 97814,
 76529,
 51778,
 88743,
 43899,
 50164,
 357463,
 131283,
 291594,
 87865,
 116067,
 115581,
 81009,
 105170,
 224120,
 7815,
 30724,
 290743,
 22088,
 73487,
 38755,
 173141,
 125271,
 84774,
 195958,
 87998,
 24977,
 7785,
 27849,
 105475,
 68568,
 340406,
 28310,
 32001,
 53454,
 164682,
 7246,
 92844,
 521,
 10760,
 103340,
 106541,
 44607,
 52923,
 45841,
 7372,
 83668,
 18350,
 109764,
 30443,
 141474,
 134346,
 110595,
 81001,
 175369,
 114439,
 53960,
 5788,
 79921,
 59401,
 55776,
 92766,
 206284,
 174783,
 25321,
 73516,
 111414,
 176758,
 144507,
 106279,
 73582,
 99945,
 93424,
 157650,
 120594,
 7346,
 86767,
 26934,
 27095,
 166206,
 78564,
 158511,
 81013,
 211682,
 100182,
 95640,
 74606,
 79012,
 84942,
 66272,
 38413,
 89475,
 33661,
 100929,
 9795,
 182972,
 162383,
 280918,
 112926,
 2144,
 186269,
 38941,
 92160,
 175051,
 217464,
 81468,
 60428,
 18682,
 90782,
 44527,
 88756,
 25126,
 68525,
 111182,
 70098,
 75007,
 33021,
 8499,
 120111,
 37135,
 106035,
 99897,
 52413,
 9923,
 10785,
 4680,
 67884,
 304381,
 6113,
 114461,
 166443,
 116351,
 333899,
 119868,
 229907,
 53964,
 105782,
 117867,
 93313,
 14463,
 141540,
 168224,
 24941,
 6262,
 44443,
 102301,
 8356,
 39175,
 47306,
 79881,
 28420,
 100339,
 69043,
 205574,
 50302,
 262808,
 43537,
 92922,
 164215,
 36979,
 339433,
 81514,
 204845,
 201540,
 92274,
 14639,
 114531,
 57994,
 290631,
 58524,
 84661,
 163553,
 100309,
 1067,
 259034,
 30424,
 121287,
 91048,
 167783,
 111195,
 117722,
 87167,
 44067,
 163416,
 67981,
 5621,
 88228,
 22352,
 85904,
 95750,
 58194,
 60752,
 30587,
 166181,
 43827,
 23322,
 85631,
 9281,
 81837,
 98365,
 125990,
 101650,
 93920,
 207899,
 63701,
 272894,
 95766,
 62016,
 107025,
 33924,
 231434,
 118079,
 141207,
 44458,
 54524,
 114636,
 359429,
 119289,
 18942,
 7340,
 122282,
 7435,
 12167,
 6831,
 8401,
 29467,
 115814,
 181741,
 17572,
 22256,
 194163,
 2511,
 47648,
 95866,
 114612,
 122688,
 93054,
 185372,
 82813,
 2539,
 35335,
 73983,
 43233,
 236144,
 75595,
 253793,
 102255,
 64639,
 19216,
 23271,
 118125,
 89567,
 6996,
 29533,
 70522,
 7795,
 126985,
 49407,
 90500,
 13034,
 42062,
 27818,
 25563,
 101894,
 51871,
 110628,
 21925,
 209627,
 86285,
 91250,
 64960,
 86388,
 26682,
 139216,
 106223,
 361422,
 42240,
 75374,
 88162,
 196018,
 9147,
 106000,
 69605,
 235120,
 46413,
 5729,
 4442,
 22385,
 60381,
 98944,
 118339,
 125175,
 23986,
 52961,
 108947,
 66596,
 116935,
 25679,
 118284,
 325602,
 14895,
 71017,
 211747,
 37161,
 162367,
 117989,
 52672,
 51686,
 85150,
 112291,
 81973,
 66184,
 201182,
 96021,
 213099,
 93587,
 47145,
 260488,
 166986,
 8005,
 28110,
 49754,
 110325,
 72467,
 40045,
 92834,
 119008,
 178522,
 47140,
 342636,
 131492,
 76181,
 20449,
 59903,
 144208,
 13212,
 97883,
 552,
 63787,
 59910,
 35705,
 67467,
 33762,
 78787,
 16478,
 81522,
 21126,
 12543,
 203499,
 95585,
 47293,
 219,
 116253,
 167368,
 27083,
 106143,
 213289,
 15251,
 56516,
 40838,
 124763,
 85107,
 125355,
 147865,
 58415,
 8482,
 83252,
 111299,
 85536,
 15360,
 49783,
 48282,
 14764,
 80331,
 97684,
 227493,
 3649,
 125837,
 92964,
 16535,
 28627,
 110596,
 1195,
 4570,
 146717,
 20593,
 259170,
 25097,
 108858,
 188580,
 105748,
 67197,
 183032,
 94877,
 196951,
 29943,
 264419,
 211520,
 17899,
 100510,
 12828,
 120005,
 29290,
 88143,
 159329,
 74306,
 105587,
 93620,
 140653,
 44490,
 60131,
 119347,
 23544,
 119901,
 100393,
 166224,
 203958,
 50983,
 14271,
 67188,
 210014,
 152055,
 7565,
 125205,
 123623,
 177104,
 118094,
 25737,
 1462,
 84107,
 95820,
 101690,
 135920,
 125730,
 70683,
 28221,
 116597,
 74515,
 133128,
 8625,
 32799,
 42821,
 33181,
 65676,
 333962,
 157414,
 37506,
 97444,
 121256,
 204209,
 974,
 78809,
 111121,
 338130,
 70097,
 55977,
 89778,
 111438,
 125288,
 41113,
 102880,
 37703,
 32577,
 16916,
 106063,
 131278,
 61780,
 27027,
 37437,
 14290,
 46416,
 27234,
 102515,
 34492,
 75171,
 48104,
 73994,
 256144,
 75786,
 39834,
 3591,
 48384,
 86105,
 23203,
 40342,
 40924,
 87783,
 105216,
 121209,
 59899,
 203031,
 198652,
 102917,
 45587,
 168236,
 31221,
 62140,
 54014,
 36750,
 207370,
 148601,
 118098,
 48212,
 120709,
 25057,
 154226,
 25544,
 16287,
 130973,
 68707,
 91758,
 20165,
 114939,
 73065,
 65113,
 115585,
 50312,
 106537,
 15680,
 89637,
 133435,
 41232,
 101214,
 192149,
 277831,
 67439,
 81643,
 106292,
 167013,
 116355,
 18434,
 166160,
 3461,
 27232,
 135457,
 106200,
 31959,
 175854,
 119369,
 125549,
 46943,
 42237,
 80058,
 45843,
 79834,
 102315,
 31444,
 43112,
 121472,
 170923,
 123701,
 112525,
 8992,
 353020,
 181611,
 111087,
 79425,
 259567,
 49582,
 52288,
 228902,
 45121,
 255687,
 272070,
 200058,
 156575,
 117923,
 49602,
 119848,
 64502,
 95463,
 70308,
 63712,
 102129,
 13579,
 48969,
 31440,
 285594,
 81513,
 108803,
 45117,
 2761,
 202675,
 38666,
 150157,
 199908,
 170136,
 187854,
 118229,
 12402,
 38609,
 4988,
 118019,
 149556,
 144825,
 226914,
 18075,
 48337,
 26350,
 34944,
 1815,
 12379,
 91712,
 41463,
 55729,
 142636,
 2714,
 93230,
 54525,
 206430,
 38069,
 51495,
 59508,
 21403,
 76822,
 41584,
 103147,
 129667,
 307445,
 42149,
 168178,
 67910,
 77117,
 158491,
 39561,
 114915,
 26876,
 118970,
 197789,
 197177,
 45463,
 202128,
 41287,
 31240,
 63093,
 34396,
 46351,
 120789,
 146060,
 110032,
 8314,
 91274,
 125222,
 81263,
 37145,
 56285,
 203383,
 91734,
 84793,
 95222,
 77182,
 14285,
 198707,
 168863,
 21074,
 49426,
 5299,
 24962,
 32472,
 43928,
 8208,
 71740,
 101342,
 7275,
 116384,
 81412,
 87012,
 37776,
 212322,
 345224,
 35317,
 161341,
 10716,
 4744,
 120721,
 118582,
 105679,
 100275,
 120312,
 61566,
 170767,
 62954,
 2095,
 3196,
 121966,
 175506,
 67772,
 93430,
 47273,
 191797,
 79740,
 113497,
 183004,
 122868,
 81419,
 82069,
 33703,
 60298,
 213553,
 149223,
 24000,
 18927,
 198573,
 209663,
 50131,
 87073,
 76880,
 11540,
 334383,
 64187,
 25009,
 93011,
 12524,
 124166,
 64047,
 119422,
 114719,
 119693,
 117021,
 7944,
 68930,
 43476,
 83860,
 81922,
 202524,
 275009,
 119531,
 32703,
 273562,
 84182,
 104838,
 188863,
 230256,
 5641,
 178928,
 199672,
 32487,
 27794,
 ...]

In [11]:
# calculating click_frequency and statistics

freq_dict = {}
for (i, m, M, n) in zip(ip, min_time, max_time, num_clicks):
    # skip if only 1 click occurred
    if M - m == 0:
        freq_dict[i] = 0
    else:
        freq_dict[i] = n / (M - m)
        
df['click_freq_for_ip'] = df.apply(lambda row: (freq_dict[row["ip"]]) , axis=1)

# data analysis on frequency list
freqs = list(freq_dict.values())
average_freq = sum(freqs)/len(freq_dict)
average_period = 1/average_freq
arr = np.array(freqs)
stdev = np.std(arr)
outliers = arr[(arr - np.mean(arr)) > 2 * np.std(arr)]
print(outliers)
#np.max(arr)

[0.125      0.08       1.         2.         2.         0.07407407
 2.         0.14285714 2.         0.08       0.05555556 0.08695652
 0.22222222 0.22222222 0.15384615 0.33333333 0.0625     0.0952381
 0.08       0.28571429 2.        ]

### Click time delta

In [21]:
ip_prev_click_time = {}

def hash_id(row, attributes):
    return ''.join(str(row[a]) for a in attributes)


def click_time_delta(row, attributes):
    uid = hash_id(row, attributes)
    prev_click_time = ip_prev_click_time.get(uid)
    ip_prev_click_time[uid] = row["click_time_dt"]
    if prev_click_time:
        return abs(row["click_time_dt"] - prev_click_time)
    else:
        return row["click_time_dt"]

df = df.sort_values(by='click_time_dt')
df['prev_click_time_delta_for_ip'] = df.apply(lambda row: click_time_delta(row, ["ip"]) , axis=1)
df['prev_click_time_delta_for_ip_os_device'] = df.apply(lambda row: click_time_delta(row, ["ip", "os", "device"]) , axis=1)
df['prev_click_time_delta_for_ip_app_os_device'] = df.apply(lambda row: click_time_delta(row, ["ip", "app", "os", "device"]) , axis=1)
df['prev_click_time_delta_for_ip_app'] = df.apply(lambda row: click_time_delta(row, ["ip", "app"]) , axis=1)

In [22]:
ip_prev_click_time = {}

df = df.sort_values(by='click_time_dt', ascending=False)
df['next_click_time_delta_for_ip'] = df.apply(lambda row: click_time_delta(row, ["ip"]) , axis=1)
df['next_click_time_delta_for_ip_os_device'] = df.apply(lambda row: click_time_delta(row, ["ip", "os", "device"]) , axis=1)
df['next_click_time_delta_for_ip_app_os_device'] = df.apply(lambda row: click_time_delta(row, ["ip", "app", "os", "device"]) , axis=1)
df['next_click_time_delta_for_ip_app'] = df.apply(lambda row: click_time_delta(row, ["ip", "app"]) , axis=1)

df

,ip,app,device,os,channel,click_time,attributed_time,is_attributed,time_to_attribution,hour_of_day,...,click_time_dt,click_freq_for_ip,prev_click_time_delta_for_ip,prev_click_time_delta_for_ip_os_device,prev_click_time_delta_for_ip_app_os_device,prev_click_time_delta_for_ip_app,next_click_time_delta_for_ip,next_click_time_delta_for_ip_os_device,next_click_time_delta_for_ip_app_os_device,next_click_time_delta_for_ip_app
23038,44018,13,1,19,477,2017-11-09 15:59:51,NaN,0,,15,...,1.505146e+09,0.000000e+00,3.350700e+04,3.350700e+04,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
41817,11911,1,1,22,115,2017-11-09 15:59:46,NaN,0,,15,...,1.505146e+09,0.000000e+00,2.691545e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
17634,81374,14,1,25,118,2017-11-09 15:59:44,NaN,0,,15,...,1.505146e+09,9.335306e-07,5.375884e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
83818,91779,18,1,41,379,2017-11-09 15:59:43,NaN,0,,15,...,1.505146e+09,7.597260e-07,5.411012e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
75024,85592,12,1,13,145,2017-11-09 15:59:42,NaN,0,,15,...,1.505146e+09,0.000000e+00,1.127500e+04,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
40708,45248,11,1,17,173,2017-11-09 15:59:41,NaN,0,,15,...,1.505146e+09,5.146747e-05,1.954700e+04,3.044000e+04,1.505146e+09,5.401308e+06,1.505146e+09,1.505146e+09,1.505146e+09,5.401308e+06
54485,110811,8,1,13,145,2017-11-09 15:59:39,NaN,0,,15,...,1.505146e+09,0.000000e+00,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
89994,80992,20,1,13,259,2017-11-09 15:59:36,NaN,0,,15,...,1.505146e+09,0.000000e+00,2.683613e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
69075,48282,18,1,13,449,2017-11-09 15:59:34,NaN,0,,15,...,1.505146e+09,3.729248e-07,1.200000e+03,2.866000e+03,1.505146e+09,6.180000e+03,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
15653,346195,7,1,13,101,2017-11-09 15:59:33,NaN,0,,15,...,1.505146e+09,1.855005e-06,1.840400e+04,1.840400e+04,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
54122,102025,21,1,32,232,2017-11-09 15:59:33,NaN,0,,15,...,1.505146e+09,5.640335e-07,1.596000e+03,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
22886,95125,9,1,32,466,2017-11-09 15:59:27,NaN,0,,15,...,1.505146e+09,0.000000e+00,8.712000e+03,1.505146e+09,1.505146e+09,2.733294e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
13523,105560,3,1,9,130,2017-11-09 15:59:26,NaN,0,,15,...,1.505146e+09,1.105658e-06,3.270000e+02,3.333800e+04,1.505146e+09,2.445600e+04,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
51114,46351,12,1,8,145,2017-11-09 15:59:23,NaN,0,,15,...,1.505146e+09,0.000000e+00,5.224000e+03,1.505146e+09,1.505146e+09,5.224000e+03,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
18042,8661,21,1,15,128,2017-11-09 15:59:23,NaN,0,,15,...,1.505146e+09,9.387492e-07,2.576900e+04,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
11491,59064,21,1,19,232,2017-11-09 15:59:22,NaN,0,,15,...,1.505146e+09,2.608911e-06,2.693573e+06,5.378314e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
20744,925,15,1,27,3,2017-11-09 15:59:14,NaN,0,,15,...,1.505146e+09,0.000000e+00,9.363000e+03,1.505146e+09,1.505146e+09,2.656900e+04,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
69746,35973,23,1,13,30,2017-11-09 15:59:13,NaN,0,,15,...,1.505146e+09,0.000000e+00,3.706000e+03,3.706000e+03,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
62372,95199,18,1,22,107,2017-11-09 15:59:13,NaN,0,,15,...,1.505146e+09,0.000000e+00,3.390000e+03,5.498000e+04,1.505146e+09,1.067600e+04,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
85978,313217,7,1,15,101,2017-11-09 15:59:10,NaN,0,,15,...,1.505146e+09,0.000000e+00,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
91029,356778,3,1,10,211,2017-11-09 15:59:10,NaN,0,,15,...,1.505146e+09,3.983270e-05,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
45243,118475,12,1,14,265,2017-11-09 15:59:09,NaN,0,,15,...,1.505146e+09,5.660365e-07,1.214500e+04,1.505146e+09,1.505146e+09,5.282400e+04,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
70690,17231,17,1,23,128,2017-11-09 15:59:04,NaN,0,,15,...,1.505146e+09,2.203211e-06,2.017500e+04,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
54903,36589,12,1,19,265,2017-11-09 15:59:02,NaN,0,,15,...,1.505146e+09,3.498950e-05,2.687713e+06,1.505146e+09,1.505146e+09,2.687713e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
24200,196078,18,1,12,121,2017-11-09 15:59:01,NaN,0,,15,...,1.505146e+09,7.447279e-07,2.712879e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
72580,120844,27,1,10,122,2017-11-09 15:58:56,NaN,0,,15,...,1.505146e+09,0.000000e+00,3.412200e+04,5.409378e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
49074,105323,20,1,19,259,2017-11-09 15:58:55,NaN,0,,15,...,1.505146e+09,2.781815e-06,4.875000e+03,4.875000e+03,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
98559,14764,18,1,15,379,2017-11-09 15:58:55,NaN,0,,15,...,1.505146e+09,1.468519e-06,2.165000e+03,1.505146e+09,1.505146e+09,7.528000e+03,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
55959,63883,24,2,25,105,2017-11-09 15:58:51,NaN,0,,15,...,1.505146e+09,0.000000e+00,8.343000e+03,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
86422,62723,18,1,20,134,2017-11-09 15:58:47,NaN,0,,15,...,1.505146e+09,0.000000e+00,2.708874e+06,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09,1.505146e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95577,201182,3,1,13,480,2017-11-06 16:01:04,NaN,0,,16,...,1.497197e+09,5.050860e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.260000e+02,1.398300e+04,2.541963e+06,2.719800e+04
95705,16399,9,1,13,258,2017-11-06 16:01:03,NaN,0,,16,...,1.497197e+09,0.000000e+00,1.497197e+09,1.497197e+09,1.497197e+09,2.579248e+06,3.839000e+03,3.839000e+03,1.497197e+09,2.579248e+06
43996,17380,9,1,37,134,2017-11-06 16:00:55,NaN,0,,16,...,1.497197e+09,5.660726e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.539961e+06,2.545999e+06,1.497197e+09,1.497197e+09
48056,64886,12,1,19,245,2017-11-06 16:00:52,NaN,0,,16,...,1.497197e+09,0.000000e+00,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,5.219169e+06,7.902897e+06,1.497197e+09,1.497197e+09
60644,35862,18,1,19,121,2017-11-06 16:00:51,NaN,0,,16,...,1.497197e+09,1.473964e-06,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.546477e+06,1.497197e+09,1.497197e+09,1.497197e+09
7473,92921,9,1,17,134,2017-11-06 16:00:51,NaN,0,,16,...,1.497197e+09,0.000000e+00,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,5.226365e+06,5.259856e+06,1.497197e+09,1.497197e+09
20415,109173,3,1,23,409,2017-11-06 16:00:47,NaN,0,,16,...,1.497197e+09,7.416032e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.557304e+06,1.497197e+09,1.497197e+09,1.497197e+09
89397,37028,6,1,3,459,2017-11-06 16:00:47,NaN,0,,16,...,1.497197e+09,0.000000e+00,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.578164e+06,5.250511e+06,1.497197e+09,1.497197e+09
2968,95820,2,1,1,377,2017-11-06 16:00:46,NaN,0,,16,...,1.497197e+09,1.446864e-04,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.435500e+04,2.598234e+06,1.497197e+09,2.568505e+06
76169,146526,8,1,14,145,2017-11-06 16:00:43,NaN,0,,16,...,1.497197e+09,7.431632e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.556665e+06,1.497197e+09,1.497197e+09,1.497197e+09
5417,113837,8,1,28,145,2017-11-06 16:00:42,NaN,0,,16,...,1.497197e+09,0.000000e+00,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,5.226923e+06,1.497197e+09,1.497197e+09,1.497197e+09
12171,104386,8,1,13,259,2017-11-06 16:00:42,NaN,0,,16,...,1.497197e+09,3.739948e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.563360e+06,1.497197e+09,1.497197e+09,1.497197e+09
90479,69395,12,1,19,178,2017-11-06 16:00:35,NaN,0,,16,...,1.497197e+09,5.720594e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.537115e+06,2.537115e+06,5.255998e+06,5.236848e+06
12269,117898,2,1,13,452,2017-11-06 16:00:32,NaN,0,,16,...,1.497197e+09,1.136087e-06,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,3.846000e+03,2.552088e+06,7.925101e+06,2.782900e+04
13040,70532,26,1,19,121,2017-11-06 16:00:31,NaN,0,,16,...,1.497197e+09,3.789359e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.569818e+06,5.225532e+06,1.497197e+09,2.618344e+06
7062,87554,25,1,16,259,2017-11-06 16:00:25,NaN,0,,16,...,1.497197e+09,7.411846e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.371700e+04,1.497197e+09,1.497197e+09,7.934950e+06
99251,60603,9,1,13,215,2017-11-06 16:00:24,NaN,0,,16,...,1.497197e+09,1.116325e-06,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.558713e+06,5.218104e+06,1.497197e+09,1.497197e+09
77320,11011,12,1,13,328,2017-11-06 16:00:24,NaN,0,,16,...,1.497197e+09,0.000000e+00,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.586561e+06,1.497197e+09,1.497197e+09,1.497197e+09
27463,114276,9,1,18,134,2017-11-06 16:00:23,NaN,0,,16,...,1.497197e+09,3.737566e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,4.210000e+02,2.586070e+06,5.222218e+06,7.303000e+03
55624,66015,1,1,12,134,2017-11-06 16:00:23,NaN,0,,16,...,1.497197e+09,3.721163e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09
98505,1415,9,1,13,134,2017-11-06 16:00:21,NaN,0,,16,...,1.497197e+09,3.747574e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.535224e+06,1.497197e+09,1.497197e+09,1.497197e+09
7563,106524,12,1,28,178,2017-11-06 16:00:20,NaN,0,,16,...,1.497197e+09,0.000000e+00,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.563595e+06,7.911632e+06,1.497197e+09,2.566793e+06
92942,87868,15,1,19,153,2017-11-06 16:00:20,NaN,0,,16,...,1.497197e+09,0.000000e+00,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,9.105000e+03,1.497197e+09,1.497197e+09,1.497197e+09
93769,93057,15,1,19,130,2017-11-06 16:00:19,NaN,0,,16,...,1.497197e+09,2.041904e-06,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.285800e+04,2.558312e+06,1.497197e+09,2.561397e+06
7940,25705,2,1,19,205,2017-11-06 16:00:13,NaN,0,,16,...,1.497197e+09,0.000000e+00,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.444000e+03,2.602000e+03,1.083800e+04,2.444000e+03
83228,91574,3,1,17,135,2017-11-06 16:00:11,NaN,0,,16,...,1.497197e+09,7.517214e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.248000e+04,1.497197e+09,1.497197e+09,2.545852e+06
99357,73954,23,1,19,153,2017-11-06 16:00:11,NaN,0,,16,...,1.497197e+09,1.150392e-06,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,2.227000e+03,4.094000e+03,1.497197e+09,1.497197e+09
31830,5314,8,1,13,145,2017-11-06 16:00:09,NaN,0,,16,...,1.497197e+09,1.961425e-04,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.285000e+03,1.285000e+03,2.581208e+06,2.541507e+06
28314,93836,12,1,30,328,2017-11-06 16:00:09,NaN,0,,16,...,1.497197e+09,3.723053e-07,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.368000e+03,1.497197e+09,1.497197e+09,7.901288e+06
54955,48646,12,1,19,178,2017-11-06 16:00:00,NaN,0,,16,...,1.497197e+09,1.470277e-06,1.497197e+09,1.497197e+09,1.497197e+09,1.497197e+09,1.211000e+03,1.497197e+09,1.497197e+09,1.211000e+03